// react/src/components/counter.tsx
import React from 'react';
import createWebComponent from '../createWebComponent';
import { css } from '@emotion/core';

// with React/Preact and Hooks, we can create components with functions
function Counter({ initialCount = 0 }: { initialCount: number }) {
  const [count, setCount] = React.useState(initialCount);

  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);

  const blue = css`
    background-color: blue;
    color: white;
  `;

  return (
    <div>
      <h2>React</h2>
      <button css={blue} onClick={increment}>
        Increment
      </button>
      <button css={blue} onClick={decrement}>
        Decrement
      </button>
      <p>Count: {count}</p>
    </div>
  );
}

const name = 'react-counter';
const component = createWebComponent(<Counter initialCount={10} />);

export { name, component };

// vue/src/components/vue-counter.vue
<template>
  <div>
    <button @click="increment">Increment</button>
    <button @click="decrement">Decrement</button>
    <p>Count: {{ count }}</p>
  </div>
</template>

<style lang="scss" scoped>
button {
  background-color: blueviolet;
  color: white;
}
</style>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  data() {
    return {
      count: 0
    };
  },
  methods: {
    increment() {
      this.count++;
    },
    decrement() {
      this.count--;
    }
  }
});
</script>
