// react/src/components/counter.tsx
import React, { useState } from 'react';
import { createWebComponent } from '../createWebComponent';

// with React/Preact and Hooks, we can create components with functions
function Counter({ initialCount = 0 }: { initialCount: number }) {
  const [count, setCount] = useState(initialCount);

  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);

  const blueBtn = {
    backgroundColor: 'blue',
    color: 'white'
  };

  return (
    <div>
      <h2>React</h2>
      <button style={blueBtn} onClick={increment}>
        Increment
      </button>
      <button style={blueBtn} onClick={decrement}>
        Decrement
      </button>
      <p>Count: {count}</p>
    </div>
  );
}

const name = 'react-counter';
const component = createWebComponent(<Counter initialCount={10} />);

export { name, component };

// preact/src/components/counter.tsx
// @ts-ignore;
__preactDebug__; // loads preact in debug mode in development, remove in production

import { h, render, Component } from 'preact';
import { useState } from 'preact/hooks';

// with React/Preact and Hooks, we can create components with functions
function counterComponent() {
  const [count, setCount] = useState(0);

  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);

  return (
    <div>
      <h2>Preact</h2>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
      <p>Count: {count}</p>
    </div>
  );
}

class PreactRoot extends Component {
  public render() {
    return counterComponent();
  }
}

// web component wrapper
class PreactCounter extends HTMLElement {
  constructor() {
    super();
  }

  public connectedCallback() {
    const shadowRoot = this.attachShadow({ mode: 'open' });
    // create Preact/React and attach mount it to the shadow root
    render(<PreactRoot />, shadowRoot);
  }
}

const name = 'preact-counter';
export { PreactCounter as component, name };
