// stencil/src/components/stencil-counter/stencil-counter.tsx
import { Component, Host, h, Prop } from '@stencil/core';

@Component({
  tag: 'stencil-counter',
  styleUrl: 'stencil-counter.css',
  shadow: true
})
export class StencilCounter {
  @Prop() count = 0;

  #increment = () => this.count++;
  #decrement = () => this.count--;

  render() {
    return (
      <Host>
        <div>
          <h2>Stencil</h2>
          <button onClick={this.#increment}>Increment</button>
          <button onClick={this.#decrement}>Decrement</button>
          <p>Count: {this.count}</p>
        </div>
      </Host>
    );
  }
}

// angular/src/app/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-angular-counter',
  templateUrl: './counter.component.html',
  styleUrls: ['./counter.component.css']
})
export class CounterComponent {
  public count = 0;

  public increment() {
    this.count++;
  }

  public decrement() {
    this.count--;
  }
}

<div>
  <h2>Angular</h2>
  <button (click)="increment()">Increment</button>
  <button (click)="decrement()">Decrement</button>
  <p>Count: {{ count }}</p>
</div>
